
project_id = "hbkgbggctzvqffqfrmhl"
[functions.remove-background]
verify_jwt = false
[functions.generate-image-text]
verify_jwt = false
[functions.generate-love-cover]
verify_jwt = false
[functions.expand-image]
verify_jwt = false
