
project_id = "hbkgbggctzvqffqfrmhl"
[functions.generate-ideas]
verify_jwt = false
[functions.remove-background]
verify_jwt = false
[functions.generate-image-texts]
verify_jwt = false
[functions.create-checkout-session]
verify_jwt = false
