
project_id = "hbkgbggctzvqffqfrmhl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true

[auth]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true

[realtime]
enabled = true

[functions]
[functions.send-order-verification]
[functions.verify-order-code]
