-- 创建love_story_books表
CREATE TABLE IF NOT EXISTS "love_story_books" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" text UNIQUE NOT NULL,
  "title" text,
  "person_name" text,
  "status" text DEFAULT 'created',
  "timestamp" timestamptz DEFAULT now(),
  "cover_pdf" text,
  "interior_pdf" text,
  "pod_package_id" varchar,
  "print_quantity" int4 DEFAULT 1,
  "shipping_level" varchar,
  "cover_source_url" varchar,
  "interior_source_url" varchar,
  "lulu_print_job_id" varchar,
  "lulu_print_status" varchar,
  "lulu_tracking_number" varchar,
  "lulu_tracking_url" varchar,
  "recipient_phone" varchar,
  "book_size" varchar DEFAULT '6x9',
  "page_count" int4,
  "is_color" bool DEFAULT false,
  "paper_type" varchar DEFAULT 'white',
  "binding_type" varchar DEFAULT 'perfect',
  "ready_for_printing" bool DEFAULT false,
  "print_date" timestamptz,
  "last_print_attempt" timestamptz,
  "print_attempts" int4 DEFAULT 0,
  "customer_email" varchar,
  "shipping_address" jsonb,
  "shipping_option" jsonb
);

-- 添加索引以提高查询性能
CREATE INDEX IF NOT EXISTS "love_story_books_order_id_idx" ON "love_story_books" ("order_id");
CREATE INDEX IF NOT EXISTS "love_story_books_status_idx" ON "love_story_books" ("status");

-- 添加RLS策略 (Row Level Security)
ALTER TABLE "love_story_books" ENABLE ROW LEVEL SECURITY;

-- 创建允许认证用户访问自己的书籍记录的策略
CREATE POLICY "Users can view their own love story books" 
  ON "love_story_books" 
  FOR SELECT 
  USING (auth.uid()::text = customer_email);

-- 允许服务角色完全访问
CREATE POLICY "Service role has full access to love story books" 
  ON "love_story_books" 
  FOR ALL 
  USING (auth.jwt() ? 'role' AND auth.jwt()->>'role' = 'service_role');

-- 添加触发器更新时间戳
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.timestamp = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_love_story_books_timestamp
BEFORE UPDATE ON "love_story_books"
FOR EACH ROW
EXECUTE PROCEDURE update_modified_column();

-- 添加注释
COMMENT ON TABLE "love_story_books" IS 'Stores love story books information and generation status';
