// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getClientId } from '@/utils/clientId';

const SUPABASE_URL = "https://hbkgbggctzvqffqfrmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhia2diZ2djdHp2cWZmcWZybWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNDIxOTcsImV4cCI6MjA1NDcxODE5N30.17M3xzD8Yx_5EAu8EzY4ARnva21TCuEHQU85TixrAdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 创建Supabase客户端，并添加客户端ID头
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      'x-client-info': typeof window !== 'undefined' ? getClientId() : 'server',
    },
  },
});